name: Terraform Learning
 
on:
    push:
        paths:
            - "env/**"
            - ".github/workflows/terraform-template.yml"
 
jobs:
    terraform:
        runs-on: ubuntu-latest
 
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
 
            - name: Azure Login
              uses: azure/login@v2
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
 
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
 
            - name: Terraform Init
              run: terraform init
              working-directory: ./env
 
            - name: Terraform Plan
              run: terraform plan -var-file=dev.tfvars
              working-directory: ./env